### ISSUE TITLE
User story 4.4: As a user, I want to be able to add basic styling and editing to my questions

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#101]
Story points: 6
Priority: Medium
Risk: Medium

Description: 
Add text editor to question and answer

Tasks:
1) Implement from open source: https://mindmup.github.io/bootstrap-wysiwyg/
2) Backend: php script to store results from front end as a raw vchar in sql and echo it back for display
3) Reference open source licensing

**Comment by sbharti123** [comment]
![image](https://user-images.githubusercontent.com/13136704/37838520-7dfb9a90-2e8e-11e8-9f56-bde37510cda2.png)

**Comment by sbharti123** [comment]
adding acceptance test for this user story:

![image](https://user-images.githubusercontent.com/13136704/38206588-fa5011a6-3678-11e8-953f-bafe933ba8e0.png)

**Comment by sbharti123** [comment]
This user story has been completed post Sprint 4.
