### ISSUE TITLE
User story 4.6 (short) : As a web user, I want to be notified when I move away from a page without having it saved so that I do not unintentionally lose my work.

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#132]
Story point: 1
Risk: Low
Priority: High

Note that: you'll need another user story as well if you take this one as your task as this is only 1 story point

Description:

Warn user when information are not saved.

**Comment by sbharti123** [comment]
![image](https://user-images.githubusercontent.com/13136704/37837697-4ad431b0-2e8c-11e8-83af-200466a26485.png)
