### ISSUE TITLE
User story 4.2: As a user, I want to be able to follow a question or user (and unfollow)

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#139]
Story points: 10
Priority: Medium
Risk: High

Description:
- User can subscribe and unsubscribe to any questions or any other users on the website, by clicking on the subscribe/unsubscribe button next to the question or user profile page, respectively. 
- When subscribed to a question, user will get a notification in inbox whenever a new answer is added to a subscribed question. The message itself will also contain a dynamic url to the question page where the answer can be found.
- When subscribed to an user X, user will get a notification in inbox whenever X asks a question or answers a question. The message itself will also contain a dynamic url to the question page where the question or answer can be found.
- Other requirement: needs to be integrated into existing notification/inbox system

********************
# **Technical tasks
This is a full stack dev task**
*******************
Part 1: SQL

For question subscription:
- Implement a new sql table, say question_subscription, with 2 columns ( subscriber_id (the user_id of the user who wish to be subscribed obtained via $_Session) + question_id). The unique parent key of the table is the concatenation of the two columns 

For user subscription:
- Implement a new sql table, say user_subscription, with 2 columns ( subscriber_id via + subscribee_id or subscribee_username (whichever is easiest to track)). The unique parent key of the table is the concatenation of the two columns 
*******************
Part 2: Front end HTML/PHP + backend subscription system

Subscription button feature
Check user login status using PHP $_Session cookies (i.e. isset)
- If user is not login, subscription button redirects to signin page
- If user is logged in, php query search for user subscription in the above sql table. If not found, display subscribe button, if found, display unsubscribed button.

Clicking on the subscribe button adds a new entry to the SQL table
Clicking on the unsubscribe button removes the appropriate entry from the appropriate sql table

Since this is the last sprint, you should also add a good looking front end style to the subscribe button. 
******************
Part 3: PHP Notification when a subscribee asks a new question
On question submission page: 
Whenever a user adds a new question, waits for the "insert into question...." php query to complete, then add a new php query to check if the user has any subscribers: 
- if no subscribers, do nothing
- if the user does have a subscriber(s):
1) Create a new message with a title and content in table notification. Say title = "Subscriber notification". The content can contain a short explanation (e.g. "You subscribee [subscriber username] just add a new question: ...] 
2) In addition, the message should contain a dynamic link to the question requires the question_id of the question. (Since the question has just been created, you can get the last locally inserted question_id by using sql statement "SELECT LAST_INSERT_ID() as 'result'" You can refer to line 72 of answer.php to see how the existing notification system adds a message with dynamic url link and formating)
3) Add the newly created message to table notification.
4) Use the  LAST_INSERT_ID() method again, but this time to get the notification_id of your new message

The message is now created. You'll now need to send the message to the inbox of all the subscribers. To do this:

5) Query table user_subscription where subscribee_id == id of the person who just asks the new question. This will give you a list of all the subscribers. 
6) For each subscriber found in the above query, loop through 5) and insert a new value into table notification_user where notification_id is the result found in 4) and where user_id is current subscriber_id in the loop
7) Done! The subscribers are now notified

*********************
Part 4: PHP Notification when a subscribed question gets a new reply or when a subscrbee replies to a question

On answer.php: 
Whenever a user adds a new answer, waits for the "insert into answer...." php query to complete, then add a new php query to check if the question has any subscribers OR if the person who answers the question has any subscribers: 
- if no subscribers at all, do nothing
- else if the user does have a subscriber(s):
Do the same as above, but changed the title and content of the message slightly to reflect the fact that this time, it's subscribee answered a question.
- else if the question itself has a subscriber(s):
1) Create a new message with a title and content in table notification. Say title = "Subscribed question". The content can contain a short explanation (e.g. "The question [question title] you followed just got a new reply: ...] 
2) In addition, the message should contain a dynamic link to the question requires the question_id of the question. You can refer to line 72 of answer.php to see how the existing notification system adds a message with dynamic url link and formating
3) Add the newly created message to table notification.

The message is now created. You'll now need to send the message to the inbox of all the subscribers. To do this:

4) Use the  LAST_INSERT_ID() method to get the id of your new message (named "notification_id" in the table). Store this in a php variable.
5) Query table question_subscription where question_id== id of the current question (should be stored in a php variable already). This will give you a list of all the subscribers to the question 
6) For each subscriber found in the above query, loop through 5) and insert a new value into table notification_user where notification_id is the result found in 4) and where user_id is current subscriber_id in the loop
7) Done! The subscribers are now notified about the new answers to a subscribed question
***************************************************************
Part 5: Refactor old code
Before, when a user asks a question, the user will get notified whenever someone replies to the question
Now. Remove this features when part 1-4 are fully functional and tested, and change it to the new subscription system instead: whenever a user asks a new question, the user is automatically subscribed to the question, but may click on the unsubscribe button next to the question if he longer wishes to be notified.

**Comment by sbharti123** [comment]
![image](https://user-images.githubusercontent.com/13136704/37837386-6e8600bc-2e8b-11e8-867d-505f81992d17.png)

**Comment by EricKokmanian** [comment]
Decided to not proceed with this user story
