### ISSUE TITLE
User story 4.7: As a user, I want to be able to change my settings

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#140]
Story Point: 4
Risk: Medium
Priority: Medium

Description
User setting page: an user should be able to modify his email, notification setting, etc.

Including: 
Notification setting
change email
basic information

**Comment by sbharti123** [comment]
![image](https://user-images.githubusercontent.com/13136704/37836606-4914df44-2e89-11e8-8256-3658aadfe98d.png)
