### ISSUE TITLE
User Story 4.8: As a user, I want the bugs fixed and previous features improved

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#145]
Story points: 20
Risk: Medium
Priority: High

Description:
Based on acceptance test results and user story continuity.

How tasks are assigned: Developer who previously took ownership on related user story is assigned responsibility over the issue/improvement for continuity. I am available should you need help. 

Tasks:
- [x] Issue 1 : Navbar needs to be fixed on notification page, user profile page, login, sign in page @Kresten24 
- [ ] Issue 2: Dynamic page resizing: Navbar on profile page, question display table on home.php @AidaBumbu 
- [ ] Improvement 3: A user may only upvote or downvote a question once. I user may remove an upvote or downvote @EricKokmanian 
- [ ] Improvement 4: Improve home page styling: the white answer previous box styling needs to be better integrated with the background @Kresten24 
- [x] Issue 5: password reset is unsecured. Any user can reset the password of any other user knowing their username or email @TiraFire 
- [ ] Issue 6: profile page is unsecured. User email and birthday should not be made public by default @EricKokmanian 
- [x] Issue 7.1: Fix accept/refuse question icon @refatK
- [ ] Issue 7.2: Limit scope to original poster @refatK @AidaBumbu 
- [ ] Issue 8: Fix answer display order on answer page. Sort answers by upvote. @sbharti123 
- [ ] Issue 9: Improve front end answer box. Make it look more stackoverflow like @sbharti123 
- [ ] Issue 10: Improve profile page content and functionalities, history tracking, point tracking @EricKokmanian 
- [ ] Issue 11: Sign up automatically sign user in if successful @Kresten24 
- [ ] Issue 12: Ensure link redirects to appropriate page @TiraFire  
- [ ] Improvement 13: Add more travis unit tests in sprint 4 @JoComp27 @MattYu 
- [ ] Improvement 14: Fixing the formatting for the tag page @JoComp27

**Comment by sbharti123** [comment]
Not valid for acceptance test since not a feature
