### ISSUE TITLE
User story 4.9: As a user, I want to upvote and downvote a question

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#146]
Story point: 5
Risk: Low
Priority: High

Description:

Add downvote and upvote for question.
User may only vote if log in
User may only have one vote
User may retract vote

**Comment by JoComp27** [comment]
Task was completed and merge to master

**Comment by JoComp27** [comment]
Acceptance Test : 
![image](https://user-images.githubusercontent.com/13425936/37833124-e770ca12-2e80-11e8-95e5-df9526377e80.png)
