### ISSUE TITLE
Todo 2: Make sure all members are added as "collaborators" on master repo

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#2]
Members added

- [x] Ming
- [x] Refat
- [x] Jonathan
- [x] Jessica
- [x] Eric
- [x] Kersten
- [x] Sumit
- [x] Aida

**Comment by JoComp27** [comment]
Missing people:
- Aida
- Sumit
- Jessica
Yet to accept invite
- Refat

**Comment by refatK** [comment]
I'm here now.
