### ISSUE TITLE
TODO Webpage outline

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#23]
Using PHP MyAdmin Bootstrap library

**Comment by MattYu** [comment]
Great job on the sign in and sign up page!

I was wondering if feature sign up info "phone number" and "gender selection" could be omitted in a later iteration. Those two fields are currently not supported by the backend SQL database

**Comment by MattYu** [comment]
Hi, I added a home.html file to the web outline using bootstrap
