### ISSUE TITLE
User Story 2: As a user, I want to be able to see and answer questions

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#30]
Story points: 8
Risk: medium-high

Technical requirements:
 

- On the home page, have a php script that fetches and displays previously asked questions stored in mysql server under table "Questions" (see .sql code for the table structure - additional dummy local questions may need to be created to help you develop this feature).*

Tip: In PHP, you might need to use sql query: SELECT question_title FROM QUESTIONS where …. limit …. order by ...). 

- When clicking on a question from the main page:

   - create a new dynamic hyperlink showing the question, 
   - + all its answers (Module/code to be written by person in charge of user story 3)
   - Have a html form allowing users to enter new answer at the button.
   - When user submits a new answer, have a PHP script that store the answer in mysql, correctly associating the answer to its parent question (php calling a sql "insert value into" statement).

For now, displaying questions in any order would do. Later on, or if you have the time, we can make the select statement for specific (latest, top, most viewed, etc.).

**Comment by JoComp27** [comment]
I'm trying to work on the first part at this moment, could you guys try to work on the part about answering questions?

**Comment by MattYu** [comment]
@JoComp27  I could look into that

**Comment by Kresten24** [comment]
I'll start working on it tomorrow. I was working on weekend.

**Comment by MattYu** [comment]
I've added a pull request containing my final built for user story 2. Please have a look at it and tell me if it suits you

**Comment by MattYu** [comment]
*Acceptance criteria*

1) User can browse questions
2) All questions can be found while browsing
3) User can answer questions he wants to answer

Acceptance test

When on the home page, user can see all questions. 
Clicking on the question links opens a link where user can reply and see the questions along the answer

Issue
- Browsing preview does not show username next to question
- Home/hot feature is not fully operational.

**Comment by MattYu** [comment]
![image](https://user-images.githubusercontent.com/23249533/37223157-990ec088-239d-11e8-95fb-75c24ebea5dc.png)
