### ISSUE TITLE
User story 5 : Setting up testing environment

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#39]
As mentionned in class and in the powerpoint documents, during Sprint 2, we will have to set up our testing environment.
Story Point : 1
People Required : 1

The one that is proposed in the documents is TravisCI.

TravisCI is a testing software which works inside of git to attempt to enable testing for projects

This is what this task will encompass : 
- Set up TravisCI
- Make a .travic.yml file to set up the TravisCI

**Comment by JoComp27** [comment]
Was done by Feb 10th

**Comment by MattYu** [comment]
*Acceptance criteria*

- Testing environment should feature basic unit test 
- Testing environment should verify every commit

Acceptance test
- When submitting a commit, each commit is tested against Composer/Travis

Issue
- More unit test is needed
