### ISSUE TITLE
User story #7: Sign in & Sign Up

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#48]
Story points: 10
Priority: High
Risk: Medium-High

Tasks:
***************************************************
Using PHP session()
UI & Design at developer discretion

Ask question: 
- check sign in -> if not, redirect to sign in page, if yes -> accept
- When asking questions, store user id in sql along with question

Answer question:
- Validate whether user is sign in before allowing user to answer a question
- When answering questions, store user id in sql along with answer

Sign in & sign up page
- Populate the backend code.
- Link sign in & sign up page with navbar

Refactor code to show user name next to answers & questions
- On the home page, next to asked on ...
- On the answer page, underneath the question
- On the answer page, next to the answers

Optional -> Dynamic Task Bars. Task bar changes depending on whether user is sign in or not. "Sign in" "Signup" is only shown if the user does not have a session

**Comment by MattYu** [comment]
Hi, I added a few clarifications for the specific tasks associated with this user story

**Comment by MattYu** [comment]
*Acceptance criteria*
- Website differentiate when user is signed or not
- When a user is sign in, the session is persistent (cookie) and may be validated
- Sign in must be secured 
- Sign out must be secured

Acceptance test
Issue
- [FIXED on #92 ]: Sign in does not support more than 1 active user
- [FIXED on #92]: Sign in does not correctly associate user to the right account

**Comment by TiraFire** [comment]
![image](https://user-images.githubusercontent.com/25015601/37223253-f291e93c-239d-11e8-9982-883cde00c848.png)

**Comment by AidaBumbu** [comment]
![image](https://user-images.githubusercontent.com/35665774/38779968-eb00bcbc-409d-11e8-9361-1f41fcc0034f.png)
