### ISSUE TITLE
TODO 1: Pick team meeting time

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#6]

**Comment by JoComp27** [comment]
Jonathan's & Aida's (We have the same schedule) Schedule : 
![image](https://user-images.githubusercontent.com/13425936/35337265-aea4319e-00e8-11e8-9a58-f95d9d83ed3a.png)

Eric's Schedule : 
![image](https://user-images.githubusercontent.com/13425936/35337293-bf90c4cc-00e8-11e8-9d6f-621a386ecef5.png)

Refat's Schedule : 
![image](https://user-images.githubusercontent.com/13425936/35337311-d1344dac-00e8-11e8-97c9-df416e5b64eb.png)

Kresten's Schedule : 
![image](https://user-images.githubusercontent.com/13425936/35337330-dc152368-00e8-11e8-8a78-7d6643345a1d.png)

Ming's Schedule:
![image](https://user-images.githubusercontent.com/13425936/35337344-e7a663c2-00e8-11e8-8b61-bcc7e80add83.png)

Jessica's Schedule:
![image](https://user-images.githubusercontent.com/13425936/35337355-ef9d6882-00e8-11e8-9195-eceaf1563ebc.png)

Sumit's Schedule :
(Hasn't given yet)

**Comment by sbharti123** [comment]
![image](https://user-images.githubusercontent.com/13136704/35340776-153423f2-00f2-11e8-881a-a209bb90b0fe.png)

**Comment by refatK** [comment]
My schedule will change so that I will be in the x marked lab, and not the open one.

Therefore, meetings on that Monday like we've done this week would be a good option.
