### ISSUE TITLE
User story 1: As a user, I want my profile page

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#65]
Story points : 7
Risk: low
priority: medium

Description : 
Page in which a user can see : 
- Every question they asked
- Every answer they answered
- Stats about their behavior of the site (Replies, Likes, upvotes on answers, etc.)
- Possibility to change user account information (bio, age, interests, tags, etc.)

Task:
- [x] Create front-end for profile page
- [x] Create backend for populating front end with appropriate data
- [x] Create access points: clicking on username name next to questions, answers brings to user page.

**Comment by MattYu** [comment]
*Acceptance criteria*

1) User profile page content is unique to the user
2) User profile page shall display all user question and answer history
3) User profile page is accessible by all users

**Comment by EricKokmanian** [comment]
![image](https://user-images.githubusercontent.com/25437099/37222375-c93abc06-239a-11e8-9150-524560bbda70.png)
