### ISSUE TITLE
User story 2: As a user, I want to get notified when someone replies to my questions

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#66]
Story points : 3 (TBD)

Description: 
- Top bar should signal a user if they answer got a comment, or, their question got an answer

**Comment by AidaBumbu** [comment]
*Acceptance criteria*

 When signed in, navigation bar will emit a signal when user's question got a comment

*Acceptance test*
A red box with the number of notifications will appear on the navigation bar next to the bell when someone answers the user's question.

**Comment by MattYu** [comment]
![image](https://user-images.githubusercontent.com/23249533/37222646-dd01c418-239b-11e8-9fac-751d0b73ea07.png)
