### ISSUE TITLE
User story 3: As a user, I want to edit and delete my questions and answers

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#67]
Story points : 4 
Risk: High
Priority: Medium 

Description : 
The user responsible for a question or answer should be able to edit or delete their questions or answers

Tasks:
- [ ] Refactor back end code to allow for deletion
- [ ] Refactor front end back UI
- [ ] Php functionality allowing communication between UI and SQL
- [ ] PHP session, limiting the scope of feature: only original poster can edit his or her question

**Comment by AidaBumbu** [comment]
*Acceptance test*
When signed in, user can delete his question or answer.
After signing out, the question/answer deleted is not visible anymore.

When signed in, user can edit his own question or answer.
After signing out, the question/answer is still modified.

**Comment by EricKokmanian** [comment]
![image](https://user-images.githubusercontent.com/25437099/37223628-200f498a-239f-11e8-9e3b-f6d8e33d4d69.png)
