### ISSUE TITLE
User story 4: As a user, I want to search questions

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#68]
Story points : 5 (TBD)

Description : 
Any user should be able to search for a specific question of their interest.

**Comment by AidaBumbu** [comment]
*Acceptance test*

Search field in the task bar
Search by character and not by words
If no characters are entered when searching, a message tells the user to enter at least one character to search
Brings the user to Search Results page when clicking search
The Search Results page outputs the questions that have the characters mentioned in the Question title or in its description

**Comment by EricKokmanian** [comment]
![image](https://user-images.githubusercontent.com/25437099/37223363-3e4966b6-239e-11e8-90a4-78803c62a64b.png)
