### ISSUE TITLE
User story 5: As a user, I want to add tags to questions

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#69]
Story points : 6

Description : 
User should be able to associate questions using tags to associate the question with its main subjects

Tasks:
- [x] Add tags when you create a question 
- [x] Display tags in the main page
- [x] Add ability to click on a tag to see questions that share the tag
- [ ] Fix Formatting for Tag page (Optional)
- [ ] Add ability to edit tags in edit questions (Needs to be done when Edit questions is added)

**Comment by JoComp27** [comment]
User Story 5 - Acceptance test
------------------------------------------

Things Added: Adding Tags

Does it work? : Yes

Comments : The key to confirm Tags is only  “,” and “ ENTER “Could try to add “SPACE” to that list- Also supposed to change the max amount of tags at once to 8

-------------------------------------------

Things Added : Tags shown for each question

Does it work? : Yes

Comments : Formatting is clean, but could look somewhat better

-------------------------------------------

Things Added : Tag Specific Webpage

Does it work? : Yes

Comments : FE formatting is not optimal (Will be made in Sprint 4)

------------------------------------------

Things Added : Removing tags (Editing Questions) 

Does it work? : Not made yet

Comments : (Will be made in sprint 4)

------------------------------------------

**Comment by EricKokmanian** [comment]
![image](https://user-images.githubusercontent.com/25437099/37223071-617818fe-239d-11e8-9e98-2c0aa00420d8.png)
