### ISSUE TITLE
User story 7: As a user, I want a good and consistent front end styling

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#79]
Story : 8 points
Risk: Low-Medium
Priority: Medium-High

Description : 
- Design a fancy welcome page for our website: Featuring short description of the website and of the team. Perhaps something like this: https://socialblue.com/, https://www.fhoke.com/ on or http://www.thecaprockgroup.com/ Styling up to developer. 
- Ensure a consistent styling on all pages (logo, task bar, background)
- Ensure smooth transitioning between pages (e.g. redirect the user to question page after finish sign up
- Design front end styling for the 1) ask question button, 2) submit button, 3) upvote/downvote button 4) Answer page (how the answers are displayed below the question) to make it look nicer
- Ensure styling holds up on window resizing  
- Possible animations à la https://www.squarespace.com/ on welcome page and/or other pages (task for sprint 3 and carry on to sprint 4) 
- Any other styling additions deemed needed by the developer(s) (please add them as tasks in the issue section)

**Comment by MattYu** [comment]
Hi, I added a new description to this user story. Please take a look above

**Comment by EricKokmanian** [comment]
![image](https://user-images.githubusercontent.com/25437099/37222700-0c2345a0-239c-11e8-9c6f-093abc051c74.png)
