### ISSUE TITLE
User story 8: As a user, I want all the previous features to work well together

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#80]
Story points: 8 points
Risk: High
Priority: High

Description: 
- Question Voting
- Showing Username next to answers and questions
- User can only upvote/downvote one
- Only creating user/super user can accept or refuse answer
- User can only answer question once (?)

**Comment by MattYu** [comment]
Additional Description:

- Upon completing the sign up form, the user should be returned to the home page and automatically logged in
- When user is logged in, the default navbar is changed to the user navbar, featuring these options: notification, profile, sign out

**Comment by EricKokmanian** [comment]
Not valid for acceptance test since not a feature
